title:              Geolonia developer's blog
description:        地図サービスの Geolonia の開発者によるブログです。
author:             Geolonia Inc.
baseurl:            ""
url:                "https://blog.geolonia.com"

future: true

# Social Profiles
twitter_username:   SBootstrap
github_username:    geoloniamap
facebook_username:  geolonia
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
